name: IKVM

on:
  push:
    branches: [ openjdk_msbuild ]
  pull_request:
    branches: [ openjdk_msbuild ]

jobs:
  build-openjdk8:
    name: Build OpenJDK 8
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Fetch OpenJDK 7
      run: mkdir -p openjdk8/build && curl -o openjdk8/build/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz "https://download.java.net/openjdk/jdk7u75/ri/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz"
    - name: Extract OpenJDK 7
      run: tar xzvf openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
      working-directory: openjdk8/build
    - name: Build OpenJDK 8
      uses: docker://debian/eol:lenny
      with:
        args: |
          bash -c '
            echo "deb http://archive.debian.org/debian/ lenny main" > /etc/apt/sources.list &&
            apt-get update &&
            apt-get install -y \
              build-essential \
              unzip \
              zip \
              curl \
              gcc-4.3 \
              g++-4.3 \
              libx11-dev \
              libxext-dev \
              libxrender-dev \
              libxtst-dev \
              libxt-dev \
              libxi-dev \
              libcups2-dev \
              libasound2-dev \
              libfreetype6-dev \
              libfontconfig1-dev &&
            JAVA_HOME=build/java-se-7u75-ri bash ./configure &&
            make DISABLE_HOTSPOT_OS_VERSION_CHECK=ok langtools corba jdk'
    - name: Package OpenJDK 8
      run: |
        zip -r openjdk8-build-linux-x86_64-normal-server-release.zip \
          linux-x86_64-normal-server-release/langtools/gensrc \
          linux-x86_64-normal-server-release/corba/gensrc \
          linux-x86_64-normal-server-release/jdk/gensrc \
          linux-x86_64-normal-server-release/jdk/impsrc \
          linux-x86_64-normal-server-release/jdk/lib \
          linux-x86_64-normal-server-release/jdk/classes
      working-directory: openjdk8/build
    - name: Upload OpenJDK 8
      uses: actions/upload-artifact@v1
      with:
        name: openjdk8-build-linux-x86_64-normal-server-release
        path: openjdk/build/openjdk8-build-linux-x86_64-normal-server-release.zip
  build-ikvm-linux:
    name: Build IKVM (Linux)
    needs:
      build-openjdk8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Download OpenJDK 8 Build
      uses: actions/download-artifact@v2
      with:
        name: openjdk8-build-linux-x86_64-normal-server-release
        path: openjdk/build
    - name: Restore OpenJDK 8 Build
      run: unzip -o openjdk8-build-linux-x86_64-normal-server-release.zip
      working-directory: openjdk8/build
    - name: DotNet Restore
      run: dotnet restore
      working-directory: ./rebuild
    - name: DotNet Build
      run: dotnet build --no-restore
      working-directory: ./rebuild
    - name: DotNet Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./rebuild
  build-ikvm-windows:
    name: Build IKVM (Windows)
    needs:
      build-openjdk8
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Download OpenJDK 8 Build
      uses: actions/download-artifact@v2
      with:
        name: openjdk8-build-linux-x86_64-normal-server-release
        path: openjdk/build
    - name: Restore OpenJDK 8 Build
      run: unzip -o openjdk8-build-linux-x86_64-normal-server-release.zip
      working-directory: openjdk8/build
    - name: DotNet Restore
      run: dotnet restore
      working-directory: ./rebuild
    - name: DotNet Build
      run: dotnet build --no-restore
      working-directory: ./rebuild
    - name: DotNet Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./rebuild
