name: IKVM

on:
  push:
    branches: [ openjdk_msbuild ]
  pull_request:
    branches: [ openjdk_msbuild ]

jobs:
  build-openjdk8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install OpenJDK 8 Tools
      run: sudo apt-get install openjdk-8-jdk-headless libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev libcups2-dev libasound2-dev libfreetype6-dev libfontconfig1-dev
    - name: Cache OpenJDK 8 Build
      uses: actions/cache@v3
      with:
        path: openjdk8/build/linux-x86_64-normal-server-release
        key: openjdk8-build-linux-x86_64-${{ hashFiles('openjdk8/**', '!openjdk/build/**') }}-1
    - name: Configure OpenJDK 8
      run: bash ./configure
      working-directory: openjdk8
    - name: Build OpenJDK 8
      run: make langtools corba jdk
      working-directory: openjdk8
    - name: Zip OpenJDK 8
      run: >
        zip -r openjdk8-build-linux-x86_64.zip
        openjdk8/build/linux-x86_64-normal-server-release/langtools/gensrc/**/*
        openjdk8/build/linux-x86_64-normal-server-release/corba/gensrc/**/*
        openjdk8/build/linux-x86_64-normal-server-release/jdk/gensrc/**/*
        openjdk8/build/linux-x86_64-normal-server-release/jdk/impsrc/**/*
        openjdk8/build/linux-x86_64-normal-server-release/jdk/lib/**/*
        openjdk8/build/linux-x86_64-normal-server-release/jdk/classes/**/*
    - name: Upload OpenJDK 8
      uses: actions/upload-artifact@v2
      with:
        name: openjdk8-build-linux-x86_64
        path: openjdk8-build-linux-x86_64.zip
  build-ikvm:
    needs:
      build-openjdk8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Download OpenJDK 8 Build
      uses: actions/download-artifact@v2
      with:
        name: openjdk8-build-linux-x86_64
        path: openjdk8-build-linux-x86_64.zip
    - name: Restore OpenJDK 8 Build
      run: unzip -o openjdk8-build-linux-x86_64.zip
    - name: Restore DotNet
      run: dotnet restore
      working-directory: ./rebuild
    - name: Build DotNet
      run: dotnet build --no-restore
      working-directory: ./rebuild
    - name: Test DotNet
      run: dotnet test --no-build --verbosity normal
      working-directory: ./rebuild
