name: IKVM

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

jobs:
  build-openjdk:
    name: Build OpenJDK
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Cache OpenJDK Build
      uses: actions/cache@v3
      with:
        path: openjdk/build/linux-x86_64-normal-server-release
        key: openjdk-build-linux-x86_64-normal-server-release--${{ runner.os }}--${{ hashFiles('openjdk/**', '!openjdk/build') }}-8
    - name: Check OpenJDK Build Stamp
      id: openjdk-build-stamp
      uses: andstor/file-existence-action@v1
      with:
        files: openjdk/build/linux-x86_64-normal-server-release/stamp
    - name: Fetch OpenJDK 7
      if: steps.openjdk-build-stamp.outputs.files_exists != 'true'
      run: |
        mkdir -p openjdk/build && 
        curl -o openjdk/build/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz "https://download.java.net/openjdk/jdk7u75/ri/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz" &&
        tar xzvf openjdk/build/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz -C openjdk/build
    - name: Build OpenJDK
      if: steps.openjdk-build-stamp.outputs.files_exists != 'true'
      uses: docker://debian/eol:lenny
      with:
        args: >
          /bin/bash -c "
            echo 'deb http://archive.debian.org/debian/ lenny main' > /etc/apt/sources.list &&
            apt-get update &&
            apt-get install -y \
              build-essential \
              unzip \
              zip \
              curl \
              gcc-4.3 \
              g++-4.3 \
              libx11-dev \
              libxext-dev \
              libxrender-dev \
              libxtst-dev \
              libxt-dev \
              libxi-dev \
              libcups2-dev \
              libasound2-dev \
              libfreetype6-dev \
              libfontconfig1-dev &&
            cd openjdk &&
            JAVA_HOME=build/java-se-7u75-ri bash ./configure &&
            make DISABLE_HOTSPOT_OS_VERSION_CHECK=ok images &&
            touch build/linux-x86_64-normal-server-release/stamp"
    - name: Update OpenJDK Attributes
      run: |
        sudo chown -R `id -u`:`id -g` linux-x86_64-normal-server-release && \
        sudo chmod -R +rwx linux-x86_64-normal-server-release/images/j2sdk-image/bin
      working-directory: openjdk/build
    - name: Package OpenJDK
      run: |
        zip -r openjdk-build-linux-x86_64-normal-server-release.zip \
          linux-x86_64-normal-server-release/langtools/gensrc \
          linux-x86_64-normal-server-release/corba/gensrc \
          linux-x86_64-normal-server-release/jdk/gensrc \
          linux-x86_64-normal-server-release/jdk/impsrc \
          linux-x86_64-normal-server-release/jdk/lib \
          linux-x86_64-normal-server-release/jdk/classes \
          linux-x86_64-normal-server-release/images
      working-directory: openjdk/build
    - name: Upload OpenJDK
      uses: actions/upload-artifact@v3
      with:
        name: openjdk-build-linux-x86_64-normal-server-release
        path: openjdk/build/openjdk-build-linux-x86_64-normal-server-release.zip
    - name: Cache OpenJDK Test Harness Build
      uses: actions/cache@v3
      with:
        path: jtreg/build
        key: jtreg-build--${{ runner.os }}--${{ hashFiles('jtreg/**', 'openjdk/build/linux-x86_64-normal-server-release/images/j2sdk-image', '!jtreg/build') }}-6
    - name: Check OpenJDK Test Harness Build Stamp
      id: jtreg-build-stamp
      uses: andstor/file-existence-action@v1
      with:
        files: jtreg/build/stamp
    - name: Build OpenJDK Test Harness
      if: steps.jtreg-build-stamp.outputs.files_exists != 'true'
      run: patch -p1 -f < ../jtreg.patch && bash make/build-all.sh `realpath ../openjdk/build/linux-x86_64-normal-server-release/images/j2sdk-image` && touch build/stamp
      working-directory: jtreg
    - name: Package OpenJDK Test Harness
      run: zip -r jtreg-build.zip build
      working-directory: jtreg
    - name: Upload OpenJDK Test Harness 
      uses: actions/upload-artifact@v3
      with:
        name: jtreg-build
        path: jtreg/jtreg-build.zip
  build-ikvm:
    name: Build IKVM (Windows)
    needs:
    - build-openjdk
    runs-on: windows-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: 5.x
    - name: Execute GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        useConfigFile: true
    - name: Setup .NET
      run: ac $env:GITHUB_ENV "`nDOTNET_INSTALL_DIR=${{ runner.temp }}\dotnet"
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup WSL
      uses: Vampire/setup-wsl@v1
      with:
        additional-packages:
          gcc
          g++
    - name: Setup NuGet
      run: ac $env:GITHUB_ENV "`nNUGET_PACKAGES=${{ runner.temp }}\nuget\packages"
    - name: Cache NuGet
      uses: actions/cache@v3
      with:
        path: ${{ runner.temp }}\nuget\packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**\*.csproj', '**\*.msbuildproj') }}
        restore-keys: ${{ runner.os }}-nuget-
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Download OpenJDK 8 Build
      uses: actions/download-artifact@v3
      with:
        name: openjdk-build-linux-x86_64-normal-server-release
        path: openjdk/build
    - name: Restore OpenJDK 8 Build
      run: unzip -o openjdk-build-linux-x86_64-normal-server-release.zip
      working-directory: openjdk/build
    - name: NuGet Restore
      run: dotnet restore IKVM.sln
    - name: Build Artifacts
      run: |
        msbuild /m:1 `
          /p:Configuration="Release" `
          /p:Platform="Any CPU" `
          /p:Version=${env:GitVersion_FullSemVer} `
          /p:AssemblyVersion=${env:GitVersion_AssemblySemVer} `
          /p:InformationalVersion=${env:GitVersion_InformationalVersion} `
          /p:FileVersion=${env:GitVersion_AssemblySemFileVer} `
          /p:PackageVersion=${env:GitVersion_NuGetVersionV2} `
          /p:RepositoryUrl="${env:GITHUB_SERVER_URL}/${env:GITHUB_REPOSITORY}.git" `
          /p:PackageProjectUrl="${env:GITHUB_SERVER_URL}/${env:GITHUB_REPOSITORY}" `
          /p:BuildInParallel=true `
          /p:CreateHardLinksForAdditionalFilesIfPossible=true `
          /p:CreateHardLinksForCopyAdditionalFilesIfPossible=true `
          /p:CreateHardLinksForCopyFilesToOutputDirectoryIfPossible=true `
          /p:CreateHardLinksForCopyLocalIfPossible=true `
          /p:CreateHardLinksForPublishFilesIfPossible=true `
          /p:ContinuousIntegrationBuild=true `
          IKVM.artifacts.msbuildproj
    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: build/nuget/*.nupkg
    - name: Package Binaries
      run: tar czvf bin.tar.gz bin
      working-directory: build
    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: bin
        path: build/bin.tar.gz
    - name: Package Tools
      run: tar czvf tools.tar.gz tools
      working-directory: build
    - name: Upload Tools
      uses: actions/upload-artifact@v3
      with:
        name: tools
        path: build/tools.tar.gz
    - name: Package Tests
      run: tar czvf tests.tar.gz tests
      working-directory: build
    - name: Upload Tests
      uses: actions/upload-artifact@v3
      with:
        name: tests
        path: build/tests.tar.gz
  test-ikvm:
    strategy:
      matrix:
        os:
        - windows
        - ubuntu
        tfm:
        - net461
        - netcoreapp3.1
        - net5.0
        - net6.0
    name: Test IKVM (${{ matrix.os }}:${{ matrix.tfm }})
    needs:
    - build-ikvm
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Download Tests
      uses: actions/download-artifact@v3
      with:
        name: tests
        path: build
    - name: Restore Tests
      run: tar xzvf tests.tar.gz
      working-directory: build
    - name: Execute Tests
      shell: pwsh
      run: $tfm="${{ matrix.tfm }}"; gci .\build\tests\*\$tfm -Recurse -Filter '*.Tests.dll' | group { $_.Directory.Parent.Name } | %{ $tst=$_.Group.Directory.Parent.Name; dotnet test $_.Group --blame -v 3 --results-directory ".\TestResults--$tfm\$tst" }
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: TestResults--${{ matrix.os }}--${{ matrix.tfm }}
        path: TestResults--${{ matrix.tfm }}
  release:
    name: Release
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    needs:
    - test-ikvm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: 5.x
    - name: Execute GitVersion
      id: GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        useConfigFile: true
    - name: Download NuGet Packages
      uses: actions/download-artifact@v3
      with:
        name: nuget
        path: build/nuget
    - name: Download Binaries
      uses: actions/download-artifact@v3
      with:
        name: bin
        path: build
    - name: Restore Binaries
      run: tar xzvf bin.tar.gz
      working-directory: build
    - name: Compress Binaries
      shell: pwsh
      run: cd build && gi bin/* | %{ $tfm = $_.Name; Push-Location "bin/$tfm"; zip -r "../IKVM-${env:GitVersion_SemVer}-bin-$tfm.zip" .; Pop-Location }
    - name: Download Tools
      uses: actions/download-artifact@v3
      with:
        name: tools
        path: build
    - name: Restore Tools
      run: tar xzvf tools.tar.gz
      working-directory: build
    - name: Compress Tools
      shell: pwsh
      run: cd build && gi tools/*/* | group { $_.Parent.Name } | %{ $tfm = $_.Name; $_.Group | %{ $rid=$_.Name; Push-Location "tools/$tfm/$rid"; zip -r "../../IKVM-${env:GitVersion_SemVer}-tools-$tfm-$rid.zip" .; Pop-Location  } }
    - name: Create Release
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event.head_commit.message == '+prerelease'
      uses: ncipollo/release-action@v1.10.0
      with:
        tag: ${{ steps.GitVersion.outputs.semVer }}
        artifacts: build/bin/*.zip,build/nuget/*.nupkg,build/tools/*.zip
        generateReleaseNotes: true
        prerelease: ${{ github.ref == 'refs/heads/develop' }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Push NuGet (GitHub)
      shell: pwsh
      run: dotnet nuget push build/nuget/*.nupkg --source $env:GITHUB_REPOS --api-key $env:GITHUB_TOKEN --skip-duplicate --no-symbols
      env:
        GITHUB_REPOS: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push NuGet (Azure DevOps)
      shell: pwsh
      run: |
        dotnet nuget add source $env:AZUREDEVOPS_REPOS --name az --username az --password $env:AZUREDEVOPS_TOKEN --store-password-in-clear-text
        dotnet nuget push build/nuget/*.nupkg --source az --api-key az --skip-duplicate --no-symbols
      env:
        AZUREDEVOPS_REPOS: https://pkgs.dev.azure.com/ikvm-revived/ikvm/_packaging/ikvm-ci/nuget/v3/index.json
        AZUREDEVOPS_TOKEN: ${{ secrets.AZUREDEVOPS_PAT }}
    - name: Push NuGet
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event.head_commit.message == '+prerelease'
      shell: pwsh
      run: dotnet nuget push build/nuget/*.nupkg --source $env:NUGET_REPOS --api-key $env:NUGET_TOKEN --skip-duplicate
      env:
        NUGET_REPOS: https://api.nuget.org/v3/index.json
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
