name: IKVM

on:
  push:
    branches: [ openjdk_msbuild ]
  pull_request:
    branches: [ openjdk_msbuild ]

jobs:
  build-openjdk8:
    name: Build OpenJDK 8
    runs-on: ubuntu-18.04
    container:
      image: debian/eol:lenny
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install OpenJDK 8 Tools
      run: |
        echo "APT::Cache-Limit \"100000000\";" >> /etc/apt/apt.conf.d/70debconf &&
        echo "deb [trusted=yes] http://archive.debian.org/debian/ lenny   main"  > /etc/apt/sources.list &&
        apt-get update &&
        apt-get install -y \
          apt \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          libxtst-dev \
          libxt-dev \
          libcups2-dev \
          libasound2-dev \
          libfreetype6-dev \
          libfontconfig1-dev \
          unzip \
          zip \
          gcc-4.3 \
          g++-4.3 &&
        echo "deb [trusted=yes] http://archive.debian.org/debian/ wheezy  main" >> /etc/apt/sources.list &&
        apt-get update &&
        apt-cache search openjdk &&
        apt-cache search gcc &&
        apt-get install -y \
          openjdk-7-jre-headless
      shell: bash
    - name: Cache OpenJDK 8 Build
      uses: actions/cache@v3
      with:
        path: openjdk8/build/linux-x86_64-normal-server-release
        key: openjdk8-build-linux-x86_64-${{ hashFiles('openjdk8/**', '!openjdk/build/**') }}-1
    - name: Configure OpenJDK 8
      run: |
        bash ./configure \
          --with-extra-cxxflags="-std=gnu++98 -Wno-error -fno-lifetime-dse -fno-delete-null-pointer-checks" \
          --with-extra-cflags="-std=gnu++98 -Wno-error -fno-lifetime-dse -fno-delete-null-pointer-checks" \
          --with-extra-ldflags=""
      working-directory: openjdk8
    - name: Build OpenJDK 8
      run: DISABLE_HOTSPOT_OS_VERSION_CHECK=ok make langtools corba jdk
      working-directory: openjdk8
    - name: Zip OpenJDK 8
      run: |
        zip -r openjdk8-build-linux-x86_64-normal-server-release.zip \
          openjdk8/build/linux-x86_64-normal-server-release/langtools/gensrc \
          openjdk8/build/linux-x86_64-normal-server-release/corba/gensrc \
          openjdk8/build/linux-x86_64-normal-server-release/jdk/gensrc \
          openjdk8/build/linux-x86_64-normal-server-release/jdk/impsrc \
          openjdk8/build/linux-x86_64-normal-server-release/jdk/lib \
          openjdk8/build/linux-x86_64-normal-server-release/jdk/classes
      shell: bash
    - name: Upload OpenJDK 8
      uses: actions/upload-artifact@v2
      with:
        name: openjdk8-build-linux-x86_64-normal-server-release
        path: openjdk8-build-linux-x86_64-normal-server-release.zip
  build-ikvm-linux:
    name: Build IKVM (Linux)
    needs:
      build-openjdk8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Download OpenJDK 8 Build
      uses: actions/download-artifact@v2
      with:
        name: openjdk8-build-linux-x86_64-normal-server-release
        path: .
    - name: Restore OpenJDK 8 Build
      run: unzip -o openjdk8-build-linux-x86_64-normal-server-release.zip
    - name: DotNet Restore
      run: dotnet restore
      working-directory: ./rebuild
    - name: DotNet Build
      run: dotnet build --no-restore
      working-directory: ./rebuild
    - name: DotNet Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./rebuild
  build-ikvm-windows:
    name: Build IKVM (Windows)
    needs:
      build-openjdk8
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Download OpenJDK 8 Build
      uses: actions/download-artifact@v2
      with:
        name: openjdk8-build-linux-x86_64-normal-server-release
        path: .
    - name: Restore OpenJDK 8 Build
      run: unzip -o openjdk8-build-linux-x86_64-normal-server-release.zip
    - name: DotNet Restore
      run: dotnet restore
      working-directory: ./rebuild
    - name: DotNet Build
      run: dotnet build --no-restore
      working-directory: ./rebuild
    - name: DotNet Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./rebuild
